### PR TITLE
Convert logging.init_app to use dictConfig

### PR DESCRIPTION
**Pull request by samuelhwilliams**
https://dluhcdigital.atlassian.net/browse/FPASF-104

### Change description
This allows each app to adjust the log configuration if needed. It moves us from an imperative log configuration flow to a declarative one - we just say what we want in a readable dict, and then logging sets it up as specified. It should be easier to debug logging issues and understand exactly what loggers we're setting up.

This will initially be used by the data-store to grab the default logging config and inject it into our new celery worker, as celery's logger needs to be set up separately (ie not via the flask app).

- [x] Unit tests and other appropriate tests added or updated
- [x] README and other documentation has been updated / added (if needed)
- [x] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

### CODE REVIEW

**Review by NarenderRajuB — DISMISSED** [review]
LGTM

**Comment by samuelhwilliams** [comment]
Sorry @NarenderRajuB - had left half a test in and a misleading commit message - just fixed that up.

**Comment by gidsg** [comment]
Does this break the existing client interface? If so should we make a major version bump to indicate?

**Comment by samuelhwilliams** [comment]
No, it doesn't / shouldn't.

**Review by gidsg — APPROVED** [review]
LGTM 👍

**Pull request merged**
